import Header from '@/components/Header/Header'
import Head from 'next/head'
import Layout from './layout'
import Planning from '@/components/Planning/Planning'
import styles from '../styles/index.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <main className={styles.main}>
          <Planning />
        </main>
      </Layout>
    </>
  )
}
