import Head from 'next/head'
import Layout from './layout'
import Planning from '@/components/Planning/Planning'
import styles from '../styles/index.module.css'
import { verify } from 'jsonwebtoken'

export default function Home({ userData }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <main className={styles.main}>
          <Planning userData={userData} />
        </main>
      </Layout>
    </>
  )
}
export async function getServerSideProps(context) {
  const { tkn } = context.req.cookies
  if (tkn) {
    const userData = verify(tkn, process.env.PASS_SECRET)
    console.log(userData.id)
    return { props: { userData } }
  }
  return { props: {} }
}
